### ISSUE TITLE
It takes quite long time to propagate registry updates

### ISSUE THREAD

**Issue by racinmat** [JuliaPackaging/PkgServer.jl#60] opened 2020-07-14 00:11 UTC
When I registered new version of package, Pkg Server didn't have it for few hours, which make running tests on Julia 1.5 on pckages using this new version fail.

**Comment by DilumAluthge** [comment] 2020-07-14 00:12
See also: https://github.com/JuliaRegistries/General/issues/16777

**Comment by DilumAluthge** [comment] 2020-07-14 00:12
It is concerning if the delay is several hours.

**Comment by johnnychen94** [comment] 2020-07-14 00:37
>  https://github.com/JuliaPackaging/PkgServer.jl/pull/57/files#r453322529
> @johnnychen94 Instead of updating it almost every second, I believe it makes more sense to update this only when there's a new registry in.

I can try to add this function to `meta` later today.

Edit: basically done, will report to JuliaRegistries/General#16777 when I collect enough data

**Comment by johnnychen94** [comment] 2020-07-15 00:23
I'm still collecting data. Here's a snapshot in my server last night: I didn't observe a registry update in pkg server in 10 hours.

![image](https://user-images.githubusercontent.com/8684355/87488912-31122480-c674-11ea-8d47-6f595e0dc97c.png)

In the meantime, there are about 24 commits to General.

**Comment by racinmat** [comment] 2020-07-15 08:27
I think this is related to the problem: https://travis-ci.community/t/very-slow-propagation-of-registry-updates-in-julia-v1-5/9335
E.g. https://travis-ci.org/github/pevnak/Mill.jl/jobs/707601390 this job is still failing, although HierarchicalUtils 1.0.0 has been merged 2 days ago https://github.com/JuliaRegistries/General/pull/17847

**Comment by johnnychen94** [comment] 2020-07-15 09:04
I think there're some failures in the storage servers. For example,

```bash
JULIA_DEPOT_PATH=$PWD/tmp JULIA_PKG_SERVER=https://us-east.storage.julialang.org julia -e 'using Pkg; pkg"add HierarchicalUtils"'
```

gives me `v0.0.9`.

Also, the kr storage server seems to be unavailable:

```bash
curl -L https://kr.storage.julialang.org/registries
*   Trying 13.125.187.173:443...
* TCP_NODELAY set
* Connected to kr.storage.julialang.org (13.125.187.173) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /Users/jc/opt/anaconda3/ssl/cacert.pem
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to kr.storage.julialang.org:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to kr.storage.julialang.org:443 
```

**Comment by giordano** [comment] 2020-07-15 09:06
> Also, the kr storage server seems to be unavailable:

It seems to be offline: https://status.julialang.org/service/kr-storage

**Comment by staticfloat** [comment] 2020-07-15 19:28
We're working on it. :) We got hit by a couple of separate failure cases at once, causing the PkgServers to stop updating their registries, the old `gen_static.jl` script to get stuck, and the new dynamic StorageServer to get stuck, all at once.

* The `gen_static.jl` script getting stuck is fixed by this: https://github.com/JuliaPackaging/PkgServer.jl/pull/63

* The `PkgServer` getting stuck is, I believe, this: https://github.com/JuliaPackaging/PkgServer.jl/pull/61

The good news is that new registries should be available now, as I have un-stuck enough of the ecosystem to get it flowing again.

**Comment by DilumAluthge** [comment] 2021-02-11 22:04
I figure it might be good to centralize this discussion into a single issue. Can we close this issue as a duplicate of https://github.com/JuliaRegistries/General/issues/16777?

**Closed as completed** 2021-02-12 01:35 UTC
